export const routes = {
  home: '/pages/home/index',
  exercises: '/pages/exercises/index',
  profile: '/pages/profile/index',
  selectTemplate: '/pages/home/select-template',
  templateDetail: '/pages/home/template-detail',
  templateEdit: '/pages/home/template-edit',
  workoutActive: '/pages/home/workout-active',
  workoutSummary: '/pages/home/workout-summary',
  workoutCalendar: '/pages/home/workout-calendar',
  weeklyReview: '/pages/home/weekly-review',
  volumeTrend: '/pages/home/volume-trend',
  historyDetail: '/pages/home/history-detail',
  planIndex: '/pages/plan/index',
  planCreate: '/pages/plan/create',
  planDetail: '/pages/plan/detail',
  planCustomize: '/pages/plan/customize',
  planCustomizePreview: '/pages/plan/customize-preview',
  planExecutionDay: '/pages/plan/execution-day',
  planActive: '/pages/plan/active',
  planEdit: '/pages/plan/edit',
  planDayEdit: '/pages/plan/day-edit',
  exerciseDetail: '/pages/exercises/detail',
  profileHistory: '/pages/profile/history',
  profileEdit: '/pages/profile/edit',
  profileBodyMetrics: '/pages/profile/body-metrics',
  profileBodyMetricHistory: '/pages/profile/body-metric-history',
  profileBodyMetricTrend: '/pages/profile/body-metric-trend',
  templateManager: '/pages/profile/template-manager',
  favorites: '/pages/profile/favorites',
  authLogin: '/pages/auth/login',
  settings: '/pages/profile/settings',
  dataPrivacy: '/pages/profile/data-privacy',
  about: '/pages/profile/about',
  membership: '/pages/profile/membership',
  onboarding: '/pages/onboarding/index',
  recommendedPlan: '/pages/onboarding/recommended-plan',
  userAgreement: '/pages/agreement/user'
} as const

export function goBack() {
  uni.navigateBack()
}
